spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prototipo
    username: andre
    password: qwepoi123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false